### ISSUE TITLE
Only expose command to certain file types

### ISSUE THREAD

**Issue by thekarel** [thekarel/vscode-open-spec-file#6]
We probably don't need `README.spec.md`

**Comment by jarekb84** [comment]
I thought of a related feature to this, in that not all files use the same suffix or even extension for their spec files. You could morph the suffix config into a map of scenarios and outcomes. Actually with this, you could extend it past spec files, and have this extension open a related file to the current one you're in. 

What I mean by that is something like

``` javascript
{
   '.js': '-spec.js', // current
   '.md': '', // do nothing, could also omit this so that only mapped files are handled by the shortcut
   '.css': '.html', // to open the corresponding markup while you're changing styles
   '.html': '.css', // reverse of above scenario
   '.scss': '.jsx', // open react component and it's corresponding style file
   '.storyboard': '.m', // logic and visual files for ios development
}
```

Could also add  a bunch of default mappings (less, sass, haml,..ect) to reduce friction in initial setup before this extension is useful, and let users define their own on top of this

This would change the use/purpose of the current functionality of openSpecfile, but making it more generic opens up usage to programmers outside of the js ecosystem (pythong, c, ruby, ect..). Thoughts?
