### ISSUE TITLE
Attempting to open a source file from a test file generates a new test file.

### ISSUE THREAD

**Issue by taylonr** [thekarel/vscode-open-spec-file#9]
I'm using version 0.0.4, which VS Code's extension gallery says is the latest version.

If I'm in a test file, e.g myFile.spec.js and I run the extension, I get a new file myFile.spec.spec.js. But what I'd expect is for it to open myFile.js.

Looking at the code, I'm unclear if this is a bug, or if the version available for VS Code doesn't have the latest commits from the repo.

**Comment by thekarel** [comment]
Thanks for reporting the issue, I'll look into it!

**Comment by taylonr** [comment]
Not sure if you saw or not, but I created a PR for this issue. #10
